version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: db-local
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    user: postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbit:
    image: rabbitmq:management
    container_name: rabbit-local
    ports:
      - '5672:5672'
      - '15672:15672'

  redis:
    image: redis:latest
    container_name: redis-local
    restart: always
    ports:
      - '6379:6379'



volumes:
  dbdata:
